<?php
$active_group = 'default';
$active_record = TRUE;
$db['default']['username'] = 'openvbx';
$db['default']['password'] = 't0@styfones';
$db['default']['hostname'] = 'joshgomez.com';
$db['default']['database'] = 'joshgomez_openvbx';
$db['default']['dbdriver'] = 'mysql';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
/* Autogenerated Configuration for db 2010-06-22 */
